import json
import os
from functools import lru_cache

from django.conf import settings


# Cached data lives in signals/data/us_tickers.json (generated by management command).
TICKERS_DATA_PATH = os.path.join(settings.BASE_DIR, "signals", "data", "us_tickers.json")


FALLBACK_TICKERS = [
    {"symbol": "AAPL", "name": "Apple Inc."},
    {"symbol": "MSFT", "name": "Microsoft Corporation"},
    {"symbol": "AMZN", "name": "Amazon.com, Inc."},
    {"symbol": "NVDA", "name": "NVIDIA Corporation"},
    {"symbol": "GOOGL", "name": "Alphabet Inc. Class A"},
    {"symbol": "META", "name": "Meta Platforms, Inc."},
    {"symbol": "TSLA", "name": "Tesla, Inc."},
    {"symbol": "SPY", "name": "SPDR S&P 500 ETF Trust"},
    {"symbol": "QQQ", "name": "Invesco QQQ Trust"},
    {"symbol": "IWM", "name": "iShares Russell 2000 ETF"},
    {"symbol": "DIA", "name": "SPDR Dow Jones Industrial Average ETF"},
    {"symbol": "VOO", "name": "Vanguard S&P 500 ETF"},
]


def _load_tickers_file():
    if not os.path.exists(TICKERS_DATA_PATH):
        return FALLBACK_TICKERS
    try:
        with open(TICKERS_DATA_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        # Expect list of {symbol, name}
        if isinstance(data, list):
            cleaned = []
            for row in data:
                if not isinstance(row, dict):
                    continue
                sym = str(row.get("symbol", "")).strip().upper()
                if not sym:
                    continue
                cleaned.append({"symbol": sym, "name": str(row.get("name", "")).strip()})
            return cleaned or FALLBACK_TICKERS
    except Exception:
        return FALLBACK_TICKERS
    return FALLBACK_TICKERS


@lru_cache(maxsize=1)
def get_us_tickers():
    """
    Returns a list of dicts: [{symbol: 'AAPL', name: 'Apple Inc.'}, ...]
    Data is cached in-process; restart server after updating tickers file.
    """
    return _load_tickers_file()

