# Generated by Django 4.2.7 on 2025-10-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Singal type name, e.g. Entry, Stop Loss, Take Profit', max_length=50, unique=True)),
                ('variables', models.JSONField(default=list, help_text="List of variables for the signal type, e.g. [{'name': 'ticker', 'type': 'string'}, {'name': 'strike', 'type': 'number'}, {'name': 'expiration', 'type': 'date'}]")),
                ('title_template', models.TextField(help_text="Template for the title of the signal e.g. '{ticker} Trade Alert'")),
                ('description_template', models.TextField(help_text="Template for the description of the signal e.g. '{{ticker}} is trading at {{strike}} and expires on {{expiration}}' will be replaced with the ticker, strike, and expiration values")),
                ('color', models.CharField(default='#000000', help_text='Color code for the signal type, e.g. #000000 for black', max_length=7)),
                ('fileds_template', models.JSONField(default=list, help_text="List of fields for the signal embed, e.g. [{'name': 'Ticker', 'value': '{{ticker}}'}, {'name': 'Strike', 'value': '{{strike}}'}, {'name': 'Expiration', 'value': '{{expiration}}'}]")),
                ('footer_template', models.TextField(help_text="Template for the footer of the signal e.g. '{{ticker}} is trading at {{strike}} and expires on {{expiration}}' will be replaced with the ticker, strike, and expiration values")),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text="Signal data stored as key-value pairs based on the signal type's variables")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signals.signaltype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
