# Generated by Django 4.2.7 on 2025-10-28 15:41

from django.db import migrations


def create_default_signal_types(apps, schema_editor):
    """Create default signal types with their templates"""
    SignalType = apps.get_model('signals', 'SignalType')
    
    default_types = [
        {
            'name': 'Trade Alert',
            'variables': [
                {'name': 'ticker', 'type': 'string', 'label': 'Ticker Symbol', 'required': True},
                # {'name': 'is_shares', 'type': 'boolean', 'label': 'Is Shares'},
                {'name': 'strike', 'type': 'float', 'label': 'Strike', 'required': True},
                {'name': 'expiration', 'type': 'date', 'label': 'Expiration', 'required': True},
                {'name': 'option_type', 'type': 'select', 'options': ['PUT', 'CALL'], 'default': 'CALL', 'label': 'Option Type', 'required': True},
                {'name': 'price', 'type': 'float', 'label': 'Price', 'required': True},
                {'name': 'targets', 'type': 'text', 'label': 'Targets', 'required': True},
                {'name': 'stop_loss', 'type': 'text', 'label': 'Stop Loss', 'required': True},
                {'name': 'trade_detail', 'type': 'text', 'label': 'Trade Detail', 'hint': (
                        'Take Profit (1): At 20% take off 50% of position and tighten up stop loss to slightly above break even\n'
                        'Take Profit (2): At 30% take off 50% of remaining position and set a 15% trailing stop loss for the remaining runners.\n'
                    )}
            ],
            'title_template': '🚨 {{ticker}} Swing Trade Alert',
            'description_template': (
                'BTO(Buy to Open)\n'
                
            ),
            'color': '#0000FF',
            'fileds_template': [
                {
                    'name': '🟢 Ticker: {{ticker}}',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '❌ Expiration',
                    'value': '{{expiration}}',
                    'inline': True
                },
                {
                    'name': '✍️ Strike',
                    'value': '{{strike}} {{option_type}}',
                    'inline': True
                },
                {
                    'name': '💵 Price',
                    'value': '${{price}}',
                    'inline': True
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '📝 **Game Plan**',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '🎯 Targets: {{targets}}',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '🛑 Stop Loss: {{stop_loss}}',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                
                {
                    'name': '💰 **Take Profit Plan**',
                    'value': ,
                    'inline': False
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '⚠️ Risk Management',
                    'value': (
                        "1. Avoid holding 0DTE/1DTE past 3PM ET unless momentum is explosive\n"
                        "2. Control Position Size\n"
                        "3. Do your own due diligence. This is not a suggestion to buy, sell or hold"
                    ),
                    'inline': False
                },
            ],
        },
        {
            'name': 'Stop Loss',
            'variables': [
                {'name': 'ticker', 'type': 'string', 'label': 'Ticker Symbol'},
                {'name': 'strike', 'type': 'float', 'label': 'Strike'},
                {'name': 'expiration', 'type': 'date', 'label': 'Expiration'},
                {'name': 'option_type', 'type': 'select', 'options': ['PUT', 'CALL'], 'default': 'CALL', 'label': 'Option Type'},
                {'name': 'price', 'type': 'float', 'label': 'Price'},
                {'name': 'entry_price', 'type': 'float', 'label': 'Entry Price'},
                {'name': 'exit_price', 'type': 'float', 'label': 'Exit Price'},
                {'name': 'pnl_percent', 'type': 'float', 'label': 'P&L %'},
            ],
            'title_template': '🛑 {{ticker}} Stop Loss HIT',
            'description_template': '🔴 **Trade Performance:**',
            'color': '#FF0000',
            'fileds_template': [
                {
                    'name': 'Ticker: {{ticker}}',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '❌ Expiration',
                    'value': '{{expiration}}',
                    'inline': True
                },
                {
                    'name': '✍️ Strike',
                    'value': '{{strike}} {{option_type}}',
                    'inline': True
                },
                {
                    'name': '💵 Price',
                    'value': '${{price}}',
                    'inline': True
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '✅ Entry',
                    'value': '${{entry_price}}',
                    'inline': True
                },
                {
                    'name': '🛑 Stop Hit',
                    'value': '${{exit_price}}',
                    'inline': True
                },
                {
                    'name': '💸 Result',
                    'value': '{{pnl_percent}}%',
                    'inline': True
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '🚨 __Status: Position Closed__ 🚨',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '🛡️ Discipline Matters: Following the plan keeps you in the game for winning trades',
                    'value': '',
                    'inline': False
                }
            ],
        },
        {
            'name': 'Take Profit',
            'variables': [
                {'name': 'ticker', 'type': 'string', 'label': 'Ticker Symbol'},
                {'name': 'strike', 'type': 'float', 'label': 'Strike'},
                {'name': 'expiration', 'type': 'date', 'label': 'Expiration'},
                {'name': 'option_type', 'type': 'select', 'options': ['PUT', 'CALL'], 'default': 'CALL', 'label': 'Option Type'},
                {'name': 'price', 'type': 'float', 'label': 'Price'},
                {'name': 'entry_price', 'type': 'float', 'label': 'Entry Price'},
                {'name': 'exit_price', 'type': 'float', 'label': 'Exit Price'},
                {'name': 'pnl_percent', 'type': 'float', 'label': 'Profit %'},
            ],
            'title_template': '🎯 {{ticker}} Take Profit HIT',
            'description_template': '**🟢 Trade Performance:**',
            'color': '#00FF00',
            'fileds_template': [
                {
                    'name': 'Ticker: {{ticker}}',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '❌ Expiration',
                    'value': '{{expiration}}',
                    'inline': True
                },
                {
                    'name': '✍️ Strike',
                    'value': '{{strike}} {{option_type}}',
                    'inline': True
                },
                {
                    'name': '💵 Price',
                    'value': '${{price}}',
                    'inline': True
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '✅ Entry',
                    'value': '${{entry_price}}',
                    'inline': True
                },
                {
                    'name': '🎯 TP Hit',
                    'value': '${{exit_price}}',
                    'inline': True
                },
                {
                    'name': '💸 Profit',
                    'value': '{{pnl_percent}}%',
                    'inline': True
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '🚨 __Status: TP Reached__ 🚨',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '',
                    'value': '\u200b',
                    'inline': False
                },
                {
                    'name': '🔍 Position Management:',
                    'value': '',
                    'inline': False
                },
                {
                    'name': '✅ Reduce position by 50% (lock in profit)',
                    'value': '',
                    'inline': False
                },
            ]
        }
    ]
    
    for signal_type_data in default_types:
        SignalType.objects.create(**signal_type_data)


def remove_default_signal_types(apps, schema_editor):
    """Remove default signal types"""
    SignalType = apps.get_model('signals', 'SignalType')
    SignalType.objects.filter(name__in=['Entry', 'Stop Loss', 'Take Profit']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_signal_types, remove_default_signal_types),
    ]
