# Generated by Django 4.2.7 on 2025-11-03 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
