# Generated by Django 4.2.7 on 2025-10-28 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def set_created_at_for_existing(apps, schema_editor):
    """Set created_at for existing SignalType records"""
    SignalType = apps.get_model('signals', 'SignalType')
    SignalType.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0004_signal_user'),
    ]

    operations = [
        # Remove unique constraint on name
        migrations.AlterField(
            model_name='signaltype',
            name='name',
            field=models.CharField(help_text='Singal type name, e.g. Entry, Stop Loss, Take Profit', max_length=50),
        ),
        # Add user field (nullable for system defaults)
        migrations.AddField(
            model_name='signaltype',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this signal type. Null for system defaults.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_types', to=settings.AUTH_USER_MODEL),
        ),
        # Add created_at and updated_at fields (nullable initially)
        migrations.AddField(
            model_name='signaltype',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='signaltype',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        # Set created_at for existing records
        migrations.RunPython(set_created_at_for_existing, migrations.RunPython.noop),
        # Now make created_at non-nullable with auto_now_add
        migrations.AlterField(
            model_name='signaltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signaltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Add unique_together constraint for name+user
        migrations.AlterUniqueTogether(
            name='signaltype',
            unique_together={('name', 'user')},
        ),
    ]
