# Generated by Django 4.2.7 on 2025-11-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_signaltype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discord_channel_name',
            field=models.CharField(blank=True, default='', help_text='Discord channel name', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discord_channel_webhook',
            field=models.URLField(blank=True, default='', help_text='Discord channel webhook URL', max_length=500),
        ),
    ]
