# Generated by Django 4.2.7 on 2025-11-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0006_alter_userprofile_discord_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discord_channel_name',
            field=models.CharField(blank=True, default='', help_text='Discord channel name (deprecated - use DiscordChannel model)', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discord_channel_webhook',
            field=models.CharField(blank=True, default='', help_text='Discord channel webhook URL (deprecated - use DiscordChannel model)', max_length=500),
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Discord channel name', max_length=255)),
                ('webhook_url', models.CharField(help_text='Discord channel webhook URL', max_length=500)),
                ('is_default', models.BooleanField(default=False, help_text='Default channel for sending signals')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'channel_name'],
                'unique_together': {('user', 'channel_name')},
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='discord_channel',
            field=models.ForeignKey(blank=True, help_text='Discord channel to send this signal to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.discordchannel'),
        ),
    ]
