# Generated by Django 4.2.7 on 2025-11-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_alter_userprofile_discord_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaltype',
            name='show_description_default',
            field=models.BooleanField(default=True, help_text='Default value for showing embed description when using this signal type'),
        ),
        migrations.AddField(
            model_name='signaltype',
            name='show_title_default',
            field=models.BooleanField(default=True, help_text='Default value for showing embed title when using this signal type'),
        ),
    ]
