# Generated by GPT-5.2 on 2026-01-14

from django.db import migrations


def _is_truthy(v):
    return v is True or v == "true" or v == 1 or v == "1"


def set_default_optional_fields(apps, schema_editor):
    """
    Ensure the built-in (user is NULL) default SignalTypes have at least a few
    optional fields enabled so the Dashboard "Optional Fields" UI appears.

    This is a data migration because many existing DBs were created before
    optional flags were added to the default templates.
    """
    SignalType = apps.get_model("signals", "SignalType")

    def update_signal_type(name, predicates):
        st = SignalType.objects.filter(user__isnull=True, name=name).first()
        if not st:
            return

        fields = st.fileds_template or []
        changed = False

        for f in fields:
            if not isinstance(f, dict):
                continue

            for pred in predicates:
                if pred(f):
                    if not _is_truthy(f.get("optional")):
                        f["optional"] = True
                        changed = True
                    break

        if changed:
            st.fileds_template = fields
            st.save(update_fields=["fileds_template"])

    # Trade Alert: allow toggling Price and Risk Management
    update_signal_type(
        "Trade Alert",
        predicates=[
            lambda f: "{{price}}" in (f.get("value") or "") or " Price" in (f.get("name") or ""),
            lambda f: "{{risk_management}}" in (f.get("value") or "") or "Risk Management" in (f.get("name") or ""),
        ],
    )

    # Stop Loss: allow toggling the motivational/disclaimer line(s)
    update_signal_type(
        "Stop Loss",
        predicates=[
            lambda f: "Discipline Matters" in (f.get("name") or "") or "Discipline" in (f.get("name") or ""),
        ],
    )

    # Take Profit: allow toggling the "Position Management" block and its checklist lines
    update_signal_type(
        "Take Profit",
        predicates=[
            lambda f: "Position Management" in (f.get("name") or ""),
            lambda f: "Reduce position" in (f.get("name") or ""),
            lambda f: "trailing stop" in (f.get("name") or "").lower(),
        ],
    )


def unset_default_optional_fields(apps, schema_editor):
    """Reverse: set all optional flags to False for the default signal types."""
    SignalType = apps.get_model("signals", "SignalType")
    for st in SignalType.objects.filter(user__isnull=True, name__in=["Trade Alert", "Stop Loss", "Take Profit"]):
        fields = st.fileds_template or []
        changed = False
        for f in fields:
            if isinstance(f, dict) and _is_truthy(f.get("optional")):
                f["optional"] = False
                changed = True
        if changed:
            st.fileds_template = fields
            st.save(update_fields=["fileds_template"])


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0008_signaltype_show_description_default_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_optional_fields, unset_default_optional_fields),
    ]

