# Generated by GPT-5.2 on 2026-01-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_single_trade_plan_to_preset(apps, schema_editor):
    UserTradePlan = apps.get_model("signals", "UserTradePlan")
    UserTradePlanPreset = apps.get_model("signals", "UserTradePlanPreset")

    for row in UserTradePlan.objects.all():
        # If user already has presets, don't force-import.
        if UserTradePlanPreset.objects.filter(user_id=row.user_id).exists():
            continue
        plan = row.plan if isinstance(row.plan, dict) else {}
        UserTradePlanPreset.objects.create(
            user_id=row.user_id,
            name="Default",
            plan=plan,
            is_default=True,
        )


def reverse_migrate_preset_to_single_trade_plan(apps, schema_editor):
    # Best-effort reverse: for users who have no UserTradePlan row, copy their default preset back.
    UserTradePlan = apps.get_model("signals", "UserTradePlan")
    UserTradePlanPreset = apps.get_model("signals", "UserTradePlanPreset")

    for preset in UserTradePlanPreset.objects.filter(is_default=True):
        if UserTradePlan.objects.filter(user_id=preset.user_id).exists():
            continue
        UserTradePlan.objects.create(user_id=preset.user_id, plan=(preset.plan if isinstance(preset.plan, dict) else {}))


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0010_usertradeplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTradePlanPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_plan_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-updated_at", "name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RunPython(migrate_single_trade_plan_to_preset, reverse_migrate_preset_to_single_trade_plan),
    ]

