# Generated by Django 4.2.7 on 2026-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0019_common_trade_alert_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='highest_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Peak price seen for trailing-stop logic (auto tracking).', max_digits=12, null=True),
        ),
    ]
